export const dummyProjectInfo = [
  {
    itemId: 1,
    itemName: "Lightup 라잇업",
    memberName: "홍길동",
    school: "서울대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-21",
    recruitStatus: false,
    viewCount: 120,
    commentCount: 8,
    likedByCurrentUser: false,
    introduce: "사용자 취향을 밝혀주는 추천 웹앱, React 프론트와 UX 라이팅에 관심 있는 분을 모집합니다.",
  },
  {
    itemId: 2,
    itemName: "UMFlight",
    memberName: "김철수",
    school: "연세대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-20",
    recruitStatus: true,
    viewCount: 95,
    commentCount: 3,
    likedByCurrentUser: true,
    introduce: "항공권 최저가 탐색/알림 서비스, React·Node·크롤링 경험자 환영합니다.",
  },
  {
    itemId: 3,
    itemName: "컬러풀",
    memberName: "이영희",
    school: "고려대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-19",
    recruitStatus: false,
    viewCount: 87,
    commentCount: 4,
    likedByCurrentUser: false,
    introduce: "팔레트 추천·접근성 대비검사 웹툴, 프론트엔드와 UI 디자이너를 찾습니다.",
  },
  {
    itemId: 4,
    itemName: "헬시핏",
    memberName: "박민수",
    school: "성균관대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-18",
    recruitStatus: true,
    viewCount: 110,
    commentCount: 7,
    likedByCurrentUser: false,
    introduce: "식단/운동 트래커 앱, 그래프 시각화와 백엔드 API 설계 경험자 모집!",
  },
  {
    itemId: 5,
    itemName: "튜터봇",
    memberName: "최지훈",
    school: "한양대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-17",
    recruitStatus: false,
    viewCount: 150,
    commentCount: 10,
    likedByCurrentUser: true,
    introduce: "LLM 기반 학습 코치 챗봇, 프롬프트 튜닝·대화 UX에 관심 있는 FE/BE 함께해요.",
  },
  {
    itemId: 6,
    itemName: "핏픽",
    memberName: "정수빈",
    school: "서강대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-16",
    recruitStatus: true,
    viewCount: 77,
    commentCount: 2,
    likedByCurrentUser: false,
    introduce: "OOTD 코디 추천 서비스, RN 모바일·이미지 처리 경험자를 기다립니다.",
  },
  {
    itemId: 7,
    itemName: "DevMate",
    memberName: "오세훈",
    school: "중앙대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-15",
    recruitStatus: false,
    viewCount: 132,
    commentCount: 6,
    likedByCurrentUser: false,
    introduce: "개발 협업 어시스턴트, Next.js·상태관리·알림 시스템 구축 가능한 분 환영.",
  },
  {
    itemId: 8,
    itemName: "로보코치",
    memberName: "한가은",
    school: "경희대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-14",
    recruitStatus: true,
    viewCount: 99,
    commentCount: 5,
    likedByCurrentUser: true,
    introduce: "AI 자세 교정 트레이너, WebRTC·포즈 추정 연동할 프론트/백엔드 구인.",
  },
  {
    itemId: 9,
    itemName: "시큐업",
    memberName: "송다혜",
    school: "이화여자대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-13",
    recruitStatus: true,
    viewCount: 80,
    commentCount: 1,
    likedByCurrentUser: false,
    introduce: "보안 학습·실습 플랫폼, Spring Security·JWT·권한 설계 경험자 우대.",
  },
  {
    itemId: 10,
    itemName: "브랜드잇",
    memberName: "서준호",
    school: "건국대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-12",
    recruitStatus: false,
    viewCount: 143,
    commentCount: 9,
    likedByCurrentUser: false,
    introduce: "스타트업 브랜딩 키트 생성 서비스, 디자이너·프론트엔드(SSR) 함께해요.",
  },
  {
    itemId: 11,
    itemName: "웹어시스트",
    memberName: "김하늘",
    school: "동국대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-11",
    recruitStatus: true,
    viewCount: 71,
    commentCount: 3,
    likedByCurrentUser: false,
    introduce: "접근성/자동화 도우미, ARIA·테스트 자동화에 관심 있는 FE/QA 모집.",
  },
  {
    itemId: 12,
    itemName: "핵쉴드",
    memberName: "정유진",
    school: "부산대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-10",
    recruitStatus: false,
    viewCount: 102,
    commentCount: 4,
    likedByCurrentUser: false,
    introduce: "게임/앱 부정행위 탐지 대시보드, 로그 파이프라인·차트 작업 함께 하실 분!",
  },
  {
    itemId: 13,
    itemName: "데이터렌즈",
    memberName: "박서연",
    school: "인하대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-09",
    recruitStatus: true,
    viewCount: 64,
    commentCount: 2,
    likedByCurrentUser: false,
    introduce: "지표 모니터링 대시보드, Recharts·React Query 최적화에 자신 있는 분 환영.",
  },
  {
    itemId: 14,
    itemName: "클라우다이즈",
    memberName: "이도현",
    school: "홍익대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-08",
    recruitStatus: true,
    viewCount: 115,
    commentCount: 6,
    likedByCurrentUser: true,
    introduce: "클라우드 비용 최적화 SaaS, 테이블/필터 UX와 API 연동 가능한 FE 구인.",
  },
  {
    itemId: 15,
    itemName: "도커스테이지",
    memberName: "강하늘",
    school: "국민대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-07",
    recruitStatus: false,
    viewCount: 90,
    commentCount: 4,
    likedByCurrentUser: false,
    introduce: "CI/CD 파이프라인 시각화 툴, 로그 스트림·상태 뱃지 UI 구현자 찾습니다.",
  },
  {
    itemId: 16,
    itemName: "ML튜너",
    memberName: "윤지원",
    school: "KAIST",
    itemImageUrl: "",
    updatedAt: "2025-07-06",
    recruitStatus: true,
    viewCount: 130,
    commentCount: 8,
    likedByCurrentUser: true,
    introduce: "하이퍼파라미터 튜닝 대시보드, 테이블/차트/태스크 상태관리 경험자 환영.",
  },
  {
    itemId: 17,
    itemName: "스타터허브",
    memberName: "문지호",
    school: "POSTECH(포항공대)",
    itemImageUrl: "",
    updatedAt: "2025-07-05",
    recruitStatus: false,
    viewCount: 74,
    commentCount: 2,
    likedByCurrentUser: false,
    introduce: "사이드프로젝트 매칭 커뮤니티, 프로필·피드·알림 구현할 FE/BE를 찾습니다.",
  },
  {
    itemId: 18,
    itemName: "코드온보딩",
    memberName: "최하람",
    school: "숭실대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-04",
    recruitStatus: true,
    viewCount: 105,
    commentCount: 5,
    likedByCurrentUser: true,
    introduce: "신입 개발자 온보딩 퀘스트 플랫폼, 미션/랭킹 UI·백엔드 API 설계 함께해요.",
  },
  {
    itemId: 19,
    itemName: "모두의PT",
    memberName: "백승민",
    school: "울산대학교",
    itemImageUrl: "",
    updatedAt: "2025-07-03",
    recruitStatus: true,
    viewCount: 89,
    commentCount: 4,
    likedByCurrentUser: false,
    introduce: "트레이너 매칭·피드백 앱, 예약·채팅·결제 플로우 구축 경험자 모집.",
  },
  {
    itemId: 20,
    itemName: "바이오캐치",
    memberName: "이하윤",
    school: "GIST(광주과학기술원)",
    itemImageUrl: "",
    updatedAt: "2025-07-02",
    recruitStatus: true,
    viewCount: 97,
    commentCount: 3,
    likedByCurrentUser: false,
    introduce: "생체신호 기반 건강 코칭, 차트/리포트 UI와 BLE 연동에 관심 있는 분 환영.",
  },
];
