import type { MyInfoProps } from "../src/types/MyInfoProps";

export const dummyMemberInfo: MyInfoProps[] = [
  {
    id: 1,
    name: "박종인",
    nickname: "일론박",
    phoneNumber: "010-1234-5678",
    email: "harrysjuns@gachon.ac.kr",
    school: "한양대학교 ERICA",
    location: "서울 전체, 경기도 성남",
    mbti: "ENTP",
    role: "PM",
    selfIntroduce: "나는 홍길동이다",
    gender: true,
    age: 23,
    skills: ["#spring", "#node.js", "#CSS", "#빅데이터분석기사"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 2,
    name: "김지우",
    nickname: "코딩왕",
    phoneNumber: "010-2345-6789",
    email: "jiwoo.kim@example.com",
    school: "고려대학교",
    location: "서울 강남구",
    mbti: "ENFP",
    role: "프론트엔드 개발",
    selfIntroduce: "UI 만드는 걸 좋아해요.",
    gender: false,
    age: 24,
    skills: ["#react", "#typescript", "#UIUX"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 3,
    name: "이현우",
    nickname: "알고짱",
    phoneNumber: "010-3456-7890",
    email: "hyeonwoo.lee@example.com",
    school: "서울대학교",
    location: "경기 수원시",
    mbti: "INTP",
    role: "알고리즘 연구",
    selfIntroduce: "PS에 진심인 편.",
    gender: true,
    age: 22,
    skills: ["#c++", "#python", "#ps"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 4,
    name: "박서연",
    nickname: "디자이너G",
    phoneNumber: "010-4567-8901",
    email: "seoyeon.park@example.com",
    school: "이화여자대학교",
    location: "서울 마포구",
    mbti: "INFP",
    role: "UI 디자이너",
    selfIntroduce: "감성 터지는 디자인을 좋아해요.",
    gender: false,
    age: 23,
    skills: ["#Figma", "#UX", "#프로토타이핑"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 5,
    name: "최민석",
    nickname: "DB박사",
    phoneNumber: "010-5678-9012",
    email: "minseok.choi@example.com",
    school: "경희대학교",
    location: "경기 고양시",
    mbti: "ESTJ",
    role: "데이터베이스 관리자",
    selfIntroduce: "데이터는 거짓말하지 않는다.",
    gender: true,
    age: 25,
    skills: ["#MySQL", "#MongoDB", "#DBA"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 6,
    name: "윤지현",
    nickname: "PM계의신",
    phoneNumber: "010-6789-0123",
    email: "jihyun.yoon@example.com",
    school: "연세대학교",
    location: "서울 관악구",
    mbti: "ENTJ",
    role: "프로덕트 매니저",
    selfIntroduce: "일정 관리의 달인.",
    gender: false,
    age: 24,
    skills: ["#Agile", "#Jira", "#Notion"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 7,
    name: "정다인",
    nickname: "테스트중",
    phoneNumber: "010-7890-1234",
    email: "dain.jung@example.com",
    school: "중앙대학교",
    location: "서울 종로구",
    mbti: "ISFP",
    role: "QA 엔지니어",
    selfIntroduce: "버그는 못 지나친다.",
    gender: true,
    age: 23,
    skills: ["#Jest", "#Cypress", "#테스트자동화"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 8,
    name: "조민재",
    nickname: "AI연구자",
    phoneNumber: "010-8901-2345",
    email: "minjae.jo@example.com",
    school: "카이스트",
    location: "서울 동작구",
    mbti: "INTJ",
    role: "AI 엔지니어",
    selfIntroduce: "LLM을 향한 사랑.",
    gender: true,
    age: 26,
    skills: ["#PyTorch", "#Tensorflow", "#LLM"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 9,
    name: "한도윤",
    nickname: "모바일러",
    phoneNumber: "010-9012-3456",
    email: "doyoon.han@example.com",
    school: "숭실대학교",
    location: "경기 성남시",
    mbti: "ISTP",
    role: "모바일 개발자",
    selfIntroduce: "모바일 퍼포먼스 최적화 장인.",
    gender: true,
    age: 25,
    skills: ["#Kotlin", "#Swift", "#ReactNative"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 10,
    name: "노지은",
    nickname: "하이브리드맨",
    phoneNumber: "010-1122-3344",
    email: "jieun.no@example.com",
    school: "한성대학교",
    location: "서울 송파구",
    mbti: "ENFJ",
    role: "크로스 플랫폼 개발자",
    selfIntroduce: "Flutter는 내 친구.",
    gender: true,
    age: 22,
    skills: ["#Flutter", "#Ionic", "#ReactNative"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 11,
    name: "배하늘",
    nickname: "그래픽러버",
    phoneNumber: "010-2233-4455",
    email: "haneul.bae@example.com",
    school: "서울예술대학교",
    location: "경기 부천시",
    mbti: "INFJ",
    role: "그래픽 디자이너",
    selfIntroduce: "감각적인 브랜드를 만듭니다.",
    gender: true,
    age: 23,
    skills: ["#Photoshop", "#Illustrator", "#Branding"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 12,
    name: "강태현",
    nickname: "웹퍼블리셔",
    phoneNumber: "010-3344-5566",
    email: "taehyun.kang@example.com",
    school: "동국대학교",
    location: "서울 중구",
    mbti: "ISTJ",
    role: "웹 퍼블리셔",
    selfIntroduce: "픽셀 단위에 진심입니다.",
    gender: true,
    age: 24,
    skills: ["#HTML", "#CSS", "#웹접근성"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 13,
    name: "김상혁",
    nickname: "보안러",
    phoneNumber: "010-4455-6677",
    email: "sanghyuk.kim@example.com",
    school: "세종대학교",
    location: "경기 의정부시",
    mbti: "ENTP",
    role: "정보보안 담당",
    selfIntroduce: "보안에 진심인 해커 출신.",
    gender: true,
    age: 25,
    skills: ["#OWASP", "#보안테스트", "#해킹방지"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 14,
    name: "이강민",
    nickname: "로봇개발자",
    phoneNumber: "010-5566-7788",
    email: "kangmin.lee@example.com",
    school: "건국대학교",
    location: "서울 노원구",
    mbti: "ESFP",
    role: "로보틱스 엔지니어",
    selfIntroduce: "센서와 로봇을 연결하는 중.",
    gender: true,
    age: 26,
    skills: ["#ROS", "#C++", "#센서"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 15,
    name: "박소영",
    nickname: "데이터러버",
    phoneNumber: "010-6677-8899",
    email: "soyoung.park@example.com",
    school: "숙명여자대학교",
    location: "서울 성북구",
    mbti: "ISTJ",
    role: "데이터 분석가",
    selfIntroduce: "숫자에 감정을 담다.",
    gender: true,
    age: 24,
    skills: ["#pandas", "#numpy", "#powerBI"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 16,
    name: "최지훈",
    nickname: "클라우드맨",
    phoneNumber: "010-7788-9900",
    email: "jihoon.choi@example.com",
    school: "경북대학교",
    location: "경기 용인시",
    mbti: "ESTP",
    role: "클라우드 엔지니어",
    selfIntroduce: "서버는 클라우드에 있다.",
    gender: true,
    age: 27,
    skills: ["#AWS", "#Azure", "#GCP"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 17,
    name: "윤소민",
    nickname: "도커박사",
    phoneNumber: "010-8899-0011",
    email: "somin.yoon@example.com",
    school: "부산대학교",
    location: "서울 은평구",
    mbti: "INFP",
    role: "DevOps 엔지니어",
    selfIntroduce: "배포는 자동화가 답이다.",
    gender: true,
    age: 25,
    skills: ["#Docker", "#Kubernetes", "#CI/CD"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 18,
    name: "정지윤",
    nickname: "ML러버",
    phoneNumber: "010-9900-1122",
    email: "jiyoon.jung@example.com",
    school: "이화여자대학교",
    location: "서울 강동구",
    mbti: "INFJ",
    role: "머신러닝 엔지니어",
    selfIntroduce: "모델 튜닝에 빠져있어요.",
    gender: true,
    age: 23,
    skills: ["#Scikit-learn", "#MLflow", "#파라미터튜닝"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 19,
    name: "조세진",
    nickname: "스타트업꿈나무",
    phoneNumber: "010-0011-2233",
    email: "sejin.jo@example.com",
    school: "광운대학교",
    location: "서울 강서구",
    mbti: "ENTP",
    role: "풀스택 개발자",
    selfIntroduce: "언젠가 나도 CEO.",
    gender: true,
    age: 24,
    skills: ["#Node.js", "#React", "#PostgreSQL"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
  {
    id: 20,
    name: "한가영",
    nickname: "테크리더",
    phoneNumber: "010-1122-3344",
    email: "gayoung.han@example.com",
    school: "홍익대학교",
    location: "경기 평택시",
    mbti: "ESTJ",
    role: "Tech Lead",
    selfIntroduce: "팀워크와 아키텍처의 조화.",
    gender: true,
    age: 27,
    skills: ["#Architecture", "#CI/CD", "#코드리뷰"],
    strengths: ["#끈기", "#성실", "#아아", "#빅데이터분석기사"],
  },
];
