import type { MyProjectCardProps } from "../src/types/MyProjectCard";

export const dummyProjectCard: MyProjectCardProps[] = [
  {
    id: 1,
    categories: ["커뮤니티", "인공지능", "세일즈"],
    title: "Lightup 라잇업",
    sub_title: "대학생들을 위한 프로젝트 연계형 창업도모 서비스",
    status: "모집마감",
    hasTeammate: true,
    current_project: false,
    applied_project: true,
    suggested_project: "applied",
    date: "2025-07-21",
  },
  {
    id: 2,
    categories: ["라이프스타일", "디자인", "로보틱스"],
    title: "UMFlight",
    sub_title: "예약, 여행정보, 피드를 하나로",
    status: "모집중",
    hasTeammate: false,
    current_project: true,
    applied_project: true,
    suggested_project: "suggested",
    date: "2025-07-20",
  },
  {
    id: 3,
    categories: ["이커머스", "마케팅", "헬스케어"],
    title: "컬러풀",
    sub_title: "사용자 감정 기반 UI 컬러 추천 플랫폼 제작",
    status: "모집마감",
    hasTeammate: false,
    current_project: false,
    applied_project: true,
    suggested_project: "suggested",
    date: "2025-07-19",
  },
  {
    id: 4,
    categories: ["마케팅", "데이터 분석", "보안"],
    title: "헬시핏",
    sub_title: "운동 루틴 기반 맞춤 영양제 추천 플랫폼",
    status: "모집중",
    hasTeammate: true,
    current_project: true,
    applied_project: false,
    suggested_project: "applied",
    date: "2025-07-18",
  },
  {
    id: 5,
    categories: ["미디어", "라이프스타일", "노코드"],
    title: "튜터봇",
    sub_title: "학생 맞춤형 AI 학습 도우미 챗봇",
    status: "모집마감",
    hasTeammate: false,
    current_project: false,
    applied_project: true,
    suggested_project: "applied",
    date: "2025-07-17",
  },
  {
    id: 6,
    categories: ["로보틱스", "ESG", "금융"],
    title: "핏픽",
    sub_title: "AI 기반 체형 맞춤 옷 추천 앱",
    status: "모집중",
    hasTeammate: false,
    current_project: false,
    applied_project: false,
    suggested_project: "suggested",
    date: "2025-07-16",
  },
  {
    id: 7,
    categories: ["교육", "디자인", "커뮤니티"],
    title: "DevMate",
    sub_title: "개발자 워크플로우를 위한 통합 도구",
    status: "모집마감",
    hasTeammate: true,
    current_project: true,
    applied_project: false,
    suggested_project: "applied",
    date: "2025-07-15",
  },
  {
    id: 8,
    categories: ["게임", "ESG", "세일즈"],
    title: "로보코치",
    sub_title: "피트니스 로봇 트레이너 플랫폼",
    status: "모집중",
    hasTeammate: false,
    current_project: false,
    applied_project: true,
    suggested_project: "suggested",
    date: "2025-07-14",
  },
  {
    id: 9,
    categories: ["디자인", "헬스케어", "보안"],
    title: "시큐업",
    sub_title: "중소기업을 위한 통합 보안 점검 도구",
    status: "모집중",
    hasTeammate: true,
    current_project: false,
    applied_project: false,
    suggested_project: "suggested",
    date: "2025-07-13",
  },
  {
    id: 10,
    categories: ["세일즈", "이커머스", "로보틱스"],
    title: "브랜드잇",
    sub_title: "스타트업을 위한 브랜딩 키트 제작 플랫폼",
    status: "모집마감",
    hasTeammate: false,
    current_project: false,
    applied_project: false,
    suggested_project: "applied",
    date: "2025-07-12",
  },
  {
    id: 11,
    categories: ["플랫폼", "교육", "ESG"],
    title: "웹어시스트",
    sub_title: "웹 접근성 자동 점검 & 수정 도구",
    status: "모집중",
    hasTeammate: true,
    current_project: true,
    applied_project: false,
    suggested_project: "suggested",
    date: "2025-07-11",
  },
  {
    id: 12,
    categories: ["헬스케어", "메타버스", "게임"],
    title: "핵쉴드",
    sub_title: "정보보안 체험형 교육 플랫폼",
    status: "모집마감",
    hasTeammate: false,
    current_project: false,
    applied_project: false,
    suggested_project: "applied",
    date: "2025-07-10",
  },
  {
    id: 13,
    categories: ["금융", "커뮤니티", "노코드"],
    title: "데이터렌즈",
    sub_title: "비즈니스용 데이터 시각화 대시보드",
    status: "모집중",
    hasTeammate: true,
    current_project: true,
    applied_project: false,
    suggested_project: "applied",
    date: "2025-07-09",
  },
  {
    id: 14,
    categories: ["교육", "게임", "디자인"],
    title: "클라우다이즈",
    sub_title: "서버리스 기반 인프라 관리 도구",
    status: "모집중",
    hasTeammate: false,
    current_project: false,
    applied_project: true,
    suggested_project: "suggested",
    date: "2025-07-08",
  },
  {
    id: 15,
    categories: ["ESG", "블록체인", "미디어"],
    title: "도커스테이지",
    sub_title: "CI/CD 자동화 파이프라인 도구",
    status: "모집마감",
    hasTeammate: true,
    current_project: false,
    applied_project: false,
    suggested_project: "suggested",
    date: "2025-07-07",
  },
  {
    id: 16,
    categories: ["금융", "보안", "세일즈"],
    title: "ML튜너",
    sub_title: "모델 성능 최적화를 위한 자동 튜닝 플랫폼",
    status: "모집중",
    hasTeammate: false,
    current_project: true,
    applied_project: true,
    suggested_project: "applied",
    date: "2025-07-06",
  },
  {
    id: 17,
    categories: ["게임", "생산성", "디자인"],
    title: "스타터허브",
    sub_title: "풀스택 개발자를 위한 MVP 빌더",
    status: "모집마감",
    hasTeammate: true,
    current_project: false,
    applied_project: false,
    suggested_project: "applied",
    date: "2025-07-05",
  },
  {
    id: 18,
    categories: ["이커머스", "마케팅", "로보틱스"],
    title: "코드온보딩",
    sub_title: "신규 팀원을 위한 온보딩 콘텐츠 생성 플랫폼",
    status: "모집중",
    hasTeammate: false,
    current_project: false,
    applied_project: true,
    suggested_project: "suggested",
    date: "2025-07-04",
  },
  {
    id: 19,
    categories: ["교육", "생산성", "인공지능"],
    title: "모두의PT",
    sub_title: "개인을 위한 AI 운동 루틴 생성기",
    status: "모집중",
    hasTeammate: true,
    current_project: false,
    applied_project: false,
    suggested_project: "applied",
    date: "2025-07-03",
  },
  {
    id: 20,
    categories: ["바이오", "헬스케어", "데이터 분석"],
    title: "바이오캐치",
    sub_title: "생체신호 기반 질병 조기 예측 서비스",
    status: "모집중",
    hasTeammate: false,
    current_project: true,
    applied_project: false,
    suggested_project: "suggested",
    date: "2025-07-02",
  },
];
