import type { ProjectData } from "../src/types/ProjectCardProps";

export const dummyProjectInfo: ProjectData[] = [
  {
    id: 1,
    user: "박종인",
    name: "대학생들을 위한 프로젝트 연계형 창업 도모 서비스, 각 파트별 팀원 모집 중",
    date: "2025-07-11",
    location: "한양대학교 ERICA",
  },
  {
    id: 2,
    user: "이코딩",
    name: "스타트업 MVP 팀원 백엔드 개발자 모집",
    date: "2025-07-13",
    location: "한양대학교 ERICA",
  },
  {
    id: 3,
    user: "박기획",
    name: "UX 리서치 기반 서비스 기획자 구합니다",
    date: "2025-07-05",
    location: "연세대학교",
  },
  {
    id: 4,
    user: "정디자이너",
    name: "브랜딩 프로젝트 참여할 디자이너 모집",
    date: "2025-07-08",
    location: "홍익대학교",
  },
  {
    id: 5,
    user: "최PM",
    name: "프로젝트 매니저 및 노션 관리 담당 구해요",
    date: "2025-07-03",
    location: "이화여자대학교",
  },
  {
    id: 6,
    user: "윤DevOps",
    name: "DevOps 및 CI/CD 파이프라인 구축 멤버",
    date: "2025-07-02",
    location: "KAIST",
  },
  {
    id: 7,
    user: "조프론트",
    name: "React + TypeScript 기반 팀원 구합니다",
    date: "2025-07-01",
    location: "성균관대학교",
  },
  {
    id: 8,
    user: "한백엔드",
    name: "NestJS 백엔드 개발자 긴급 모집중입니다",
    date: "2025-06-30",
    location: "고려대학교",
  },
  {
    id: 9,
    user: "임PM",
    name: "모바일 앱 기획 및 일정관리 PM을 찾습니다",
    date: "2025-07-06",
    location: "중앙대학교",
  },
  {
    id: 10,
    user: "노AI",
    name: "GPT 기반 추천 시스템 프로젝트 참여자 모집",
    date: "2025-07-04",
    location: "서울과학기술대학교",
  },
  {
    id: 11,
    user: "배풀스택",
    name: "Fullstack 개발자 모집 (Next.js, Supabase)",
    date: "2025-06-29",
    location: "경희대학교",
  },
  {
    id: 12,
    user: "강UIUX",
    name: "사용자 여정 기반 UI/UX 디자이너 찾습니다",
    date: "2025-06-28",
    location: "서울시립대학교",
  },
  {
    id: 13,
    user: "김분석가",
    name: "데이터 기반 마케팅 분석 프로젝트 팀원 모집",
    date: "2025-07-05",
    location: "숭실대학교",
  },
  {
    id: 14,
    user: "이QA",
    name: "QA 자동화 도입을 위한 협업 인원 모집중",
    date: "2025-07-03",
    location: "세종대학교",
  },
  {
    id: 15,
    user: "장서비스",
    name: "B2B SaaS 설계 관련 백엔드 인력 모집",
    date: "2025-06-27",
    location: "단국대학교",
  },
  {
    id: 16,
    user: "정PM",
    name: "일정관리/운영 지원 가능한 PM 구합니다",
    date: "2025-06-25",
    location: "건국대학교",
  },
];
